<div class="container">

  <div class="row PageHead">


  </div>
  <div class="row blog">
    <div class="col-md-12">
      <div class="blogpost">


        <img src="<?php echo $this->baseUrl('images/about-ea.png'); ?>" alt="blog img">
        <p>
            <br>
           Eastern Analogic è una delle aziende leader nella fornitura di <strong>apparati di networking</strong>. Nasce nel 1994 ad Ancona da un gruppo di ricercatori della <strong>Università Politecnica delle Marche</strong>, focalizzandosi sulla produzione di server. Attualmente vi lavorano oltre 6.000 persone in Italia.
        </p>
          <p>
              <br>
            Per noi di Eastern Analogic, <strong>un'esperienza digitale</strong>, significativa e completa è la chiave per entrare nel mondo digitale integrato attuale. Le aziende sono in grado di personalizzare le esperienze digitali per i propri dipendenti con contenuti mirati e personalizzati per connettersi completamente con i clienti, collaboratori e Business Partner nel modo più avanzato e produttivo.
          </p>
          <p>
              <br>
              Le soluzioni di Eastern Analogic forniscono agli utenti un <strong>accesso istantaneo</strong> alle informazioni di cui hanno bisogno, quando ne hanno bisogno. L'accessibilità è supportata da tutti i tipi di dispositivi. L'esperienza digitale produce <strong>rendimenti organizzativi complessivi maggiori</strong>, dal marketing di destinazione, all'anticipazione dei problemi del cliente, all'abbattimento delle barriere di comunicazione e altro ancora.
          </p>
      </div>

    </div>

  </div>
  <!--Blog Closed--> 
  
</div>
<!--Container Closed-->

</body>
</html>