

<!--==============HEADER =================-->
<div class="jumbotron masthead">
  <div class="container"> 
    
    <!--==============Hero Unit=================-->
    
    <div class="flexslider">
      <ul class="slides">
        <li>
          <div class="hero-unit">
            <h1 style="font-size:28px;">Documentazione del progetto</h1>
            <h3>Leggi la documentazione del progetto</h3>
            <div class="slider-actions text-center"> <a href="<?php echo $this->baseUrl('docs/documentazione-gruppo-57.pdf');?>" class="btn btn-success btn-lg">Leggi</a> </div>
          </div>
        </li>
        <li>
          <div class="slide2">
            <p><img src="<?php echo $this->baseUrl('images/server1.png'); ?>" alt="server" class="img-responsive center-block"></p>
            <h1>Prestazioni ai massimi livelli</h1>
    </div>
        </li>
        <li>
          <div class="slide3">
            <p class="pull-left"><img src="<?php echo $this->baseUrl('images/server2.png'); ?>" alt="server" class="img-responsive"></p>
            <h1>Server altamente affidabili</h1>
            <h3>I nostri server sono stati scelti da decine di clienti per la loro grande affidailità </h3>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

<!--==============Content Area=================-->

<div class="container"> 
  <!--============== Main Features ==============-->
  
  <div class="row mainFeatures" id="features">
    <div class="col-sm-6 col-md-4">
      <div class="img-thumbnail"> <img src="<?php echo $this->baseUrl('images/secure_img.png'); ?>" width="85" height="88" alt="secure">
        <div class="caption">
          <h4>Sicuri e affidabili</h4>
          <p>I nostri server sono certificati per garantire la massima sicurezza e affidabilità</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="img-thumbnail"> <img src="<?php echo $this->baseUrl('images/fast_img.png'); ?>" width="85" height="88" alt="secure">
        <div class="caption">
          <h4>Super Veloci</h4>
          <p>Le nostre tecnologie permettono di trasferire files pesanti in pochissimi secondi.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-0">
      <div class="img-thumbnail"> <img src="<?php echo $this->baseUrl('images/support_img.png'); ?>" width="85" height="88" alt="secure">
        <div class="caption">
          <h4>Supporto Clienti</h4>
          <p>Abbiamo un team dedicato e centinaia di centri assistenza in tutta Italia</p>
        </div>
      </div>
    </div>
  </div>
  
  <!--============== Other Features ==============-->
  
  <div class="row PageHead">
    <div class="col-md-12">
      <h1>Funzionalità offerte</h1>
      <h3>Tutto ciò che i nostri server possono fare</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 features"> <img src="<?php echo $this->baseUrl('images/setup_icon.png'); ?>" alt="icon" class="img-responsive">
      <h4>Setup Instantaneo</h4>
      <p>I nostri Server danno una marcia in più alla tua azienda. Facilissimi da installare, configurare e gestire, possiedono nuove funzioni che velocizzano i download sulla tua rete. </p>
    </div>
    <div class="col-sm-6 features"> <img src="<?php echo $this->baseUrl('images/backup_icon.png'); ?>" alt="icon" class="img-responsive">
      <h4>Backup Costanti</h4>
      <p>I nostri Server sono configurati per eseguire 4 backup al giorno. I tuoi dati saranno constantemente al sicuro!</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 features"> <img src="<?php echo $this->baseUrl('images/git_icon.png'); ?>" alt="icon" class="img-responsive">
      <h4>Supporto GIT/SVN</h4>
      <p>Offriamo un sistema di controllo versione attraverso il sistema GIT o SVN, accessibili rapidamente da linea di comando.</p>
    </div>
    <div class="col-sm-6 features"> <img src="<?php echo $this->baseUrl('images/cloud-icon.png'); ?>" alt="icon" class="img-responsive">
      <h4>Perfetti per il Cloud</h4>
      <p>I nostri prodotti sono particolarmente indicati per lo sviluppo di un sistema Cloud.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 features"> <img src="<?php echo $this->baseUrl('images/cpanel_icon.png'); ?>" alt="icon" class="img-responsive">
      <h4>Hardware ultramoderno</h4>
      <p>Tutti i nostri Server offrono componenti hardware tali da garantire i più alti livelli di affidabilità e prestazioni.</p>
    </div>
    <div class="col-sm-6 features"> <img src="<?php echo $this->baseUrl('images/php_icon.png'); ?>" alt="icon" class="img-responsive">
      <h4>Supporto PHP & MySQL</h4>
      <p>I nostri sistemi includono le più recenti versioni stabili di PHP e MySQL. Inoltre, noi implementiamo rigidi controlli di sicurezza per proteggere il server da attacchi DoS & DDoS</p>
    </div>
  </div>
</div>
<!--Container Closed--> 




<!--==============MODAL LOGIN=================--> 

<!-- Modal -->

<!-- /.modal --> 

<!--==============BOOTSTRAP JS=================--> 

</body>
</html>