<?php $this->headTitle('Eastern Analogic - Login'); ?>


<div class="container"> 

    <div class="row PageHead">

        <div class="col-md-12">
            <h1>Esegui il Login</h1>
            <h3>Inserisci la tua email e la tua password</h3>

        </div>
    </div>
  <div class="row blog">

    <div class="col-md-12">

      <div class="blogpost" style="width:50%; display:block; margin-left:auto; margin-right:auto;">
          <?php echo $this->loginform; ?>
      </div>
        </div>


  </div>
  <!--Blog Closed--> 
  
</div>
<!--Container Closed-->

</body>
</html>