<div class="container">

  <div class="row PageHead">


  </div>
  <div class="row blog">
    <div class="col-md-12">

      <div class="blogpost">
            <h1 style="text-align: center">Inserisci nuovo utente</h1>
          <h4 style="text-align: center">Seleziona il centro Eastern Analogic solo se l'utente è un membro dello staff.</h4>
            <div class="loginform">
                <?php echo $this->utenteform; ?>
            </div>

      </div>

    </div>

  </div>
  <!--Blog Closed--> 
  
</div>
<!--Container Closed-->

</body>
</html>