<div class="container">

  <div class="row PageHead">


  </div>
  <div class="row blog">
    <div class="col-md-12">

      <div class="blogpost">
            <h1 style="text-align: center">Inserisci Prodotto</h1>
          <h4 style="text-align: center">N.B: Il mancato inserimento di una foto comporterà l'assegnazione di una di default.</h4>
            <div class="loginform">
                <?php echo $this->prodottoform; ?>
            </div>

      </div>

    </div>

  </div>
  <!--Blog Closed--> 
  
</div>
<!--Container Closed-->

</body>
</html>