<div class="container">

  <div class="row PageHead">


  </div>
  <div class="row blog">
    <div class="col-md-12">

      <div class="blogpost">
            <h1 style="text-align: center">Inserisci Centro</h1>
          <h4 style="text-align: center">Le coordinate sono espresse in lat,long. Scopri <a href="<?php echo $this->baseUrl('images/guida-maps.jpg');?>">come trovarle</a> con Google Maps!</h4>
            <div class="loginform">
                <?php echo $this->centroform; ?>
            </div>

      </div>

    </div>

  </div>
  <!--Blog Closed--> 
  
</div>
<!--Container Closed-->

</body>
</html>