<div class="container">

  <div class="row PageHead">


  </div>
  <div class="row blog">
    <div class="col-md-12">

      <div class="blogpost">
            <h1 style="text-align: center">Modifica Utente</h1>
          <h4 style="text-align: center">Se non intendi modificare la password attuale, lascia il campo password vuoto.</h4>
            <div class="loginform">
                <?php echo $this->utenteform2; ?>
            </div>

      </div>

    </div>

  </div>
  <!--Blog Closed--> 
  
</div>
<!--Container Closed-->

</body>
</html>