<div class="container">

  <div class="row PageHead">


  </div>
  <div class="row blog">
    <div class="col-md-12">

      <div class="blogpost">
            <h1 style="text-align: center">Modifica Faq</h1>
            <div class="loginform">
                <?php echo $this->faqform2; ?>
            </div>

      </div>

    </div>

  </div>
  <!--Blog Closed--> 
  
</div>
<!--Container Closed-->

</body>
</html>